include:
  - project: $CATALOG_PATH
    file:
      - vault-ci.yml
      - kaniko-ci.yml
    ref: main


default:
  image: alpine:latest

stages:
  - read-secret
  - docker-build

read_secret:
  only:
    - web
  stage: read-secret
  extends:
    - .vault:read_secret

docker-build:
  needs: ["read_secret"]
  only:
    - web
  variables:
    IMAGE_NAME: dataloader
    DOCKERFILE: Dockerfile
    # TAG: "${CI_COMMIT_REF_SLUG}"
    TAG: "1.0"
    REGISTRY_URL: "${IMAGE_REPOSITORY}"
  stage: docker-build
  extends:
    - .kaniko:build-push