apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.dataloader.fullname }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.dataloader.AK }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.dataloader.SK }}
  ADDOK_FRANCE_BUNDLE_URL: {{ .Values.dataloader.addokFranceBundleUrl }}
  S3_ENDPOINT_URL: {{ .Values.dataloader.s3EndpointUrl }}
  S3_BUCKET: {{ .Values.dataloader.bucket }}
  AWS_OPTS: {{ .Values.dataloader.awsOpts | default "" }}
