apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.dataloader.fullname }}
spec:
  jobTemplate:
    metadata:
      name: {{ .Values.dataloader.fullname }}
    spec:
      suspend: true
      template:
        metadata:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          containers:
          - image: "{{ .Values.dataloader.image.registry }}/{{ .Values.dataloader.image.repository }}:{{ .Values.dataloader.image.tag }}"
            name: {{ .Values.dataloader.fullname }}
            envFrom:
            - configMapRef:
                name: {{ .Values.dataloader.fullname }}
            - secretRef:
                name: dataloader-s3
            resources: {}
            volumeMount: 
              - name: voltmp
                mountPath: /data/
          restartPolicy: OnFailure
          volumes:
          - name: voltmp
            emptyDir:
              sizeLimit: {{ .Values.dataloader.storage }}
  schedule: {{ .Values.dataloader.schedule }}
