apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.addokRedis.fullname }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.addokRedis.replicaCount }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "..labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "..serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.addokRedis.fullname }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.addokRedis.image.registry }}/{{ .Values.addokRedis.image.repository }}:{{ .Values.addokRedis.image.tag }}"
          imagePullPolicy: {{ .Values.addokRedis.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.addokRedis.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.addokRedis.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.addokRedis.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.addokRedis.resources | nindent 12 }}
          {{- with .Values.addokRedis.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.addokRedis.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.addokRedis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.addokRedis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.addokRedis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
