apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.addokRedis.fullname }}-init
data:
  OUTPUT_FILE: "/data/dump.rdb"
  S3_ENDPOINT_URL: "{{ .Values.dataloader.s3EndpointUrl }}"
  S3_BUCKET: "addok"
  S3_FILE: "dump.rdb"
  SSL_VERIFY_PEER: false

