apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.addokRedis.fullname }}-init
data:
  VOLDATA: "/data"
  AWS_OPTS: "--no-verify-ssl"
  S3_ENDPOINT_URL: "https://api.minio-siaf.apps.app1.numerique-interieur.com/"
  S3_BUCKET: "s3://addok/"
  S3_FILE: "dump.rdb"
