apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.addokRedis.fullname }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: {{ .Values.addokRedis.service.type }}
  ports:
    - port: {{ .Values.addokRedis.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.addokRedis.fullname }}
