{{- if .Values.addokRedis.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.addokRedis.fullname }}
  labels:
    {{- include "..labels" . | nindent 4 }}
  {{- with .Values.addokRedis.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.addokRedis.serviceAccount.automount }}
{{- end }}
