apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.addok.fullname }}-conf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.addok.conf.storage }}
