apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.addok.fullname }}-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.addok.data.storage }}
