apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.addok.fullname }}-initconf
data:
  VOLDATA: "/etc/addok"
  AWS_OPTS: {{ .Values.dataloader.awsOpts | default "" }}
  S3_ENDPOINT_URL: "{{ .Values.dataloader.s3EndpointUrl }}"
  S3_BUCKET: "{{ .Values.dataloader.bucket }}"
  S3_FILE: "addok.conf"
