apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.addok.fullname }}-initdb
data:
  OUTPUT_FILE: "/data/addok.db"
  S3_ENDPOINT_URL: "{{ .Values.dataloader.s3EndpointUrl }}"
  S3_BUCKET: "addok"
  S3_FILE: "addok.db"
  SSL_VERIFY_PEER: false
