{{- if .Values.addok.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.addok.fullname }}
  labels:
    {{- include "..labels" . | nindent 4 }}
  {{- with .Values.addok.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.addok.serviceAccount.automount }}
{{- end }}
