environment: ovh
phase: dev

dataloader:
  image:
    registry: harbor.apps.dso.numerique-interieur.com
    repository: mi-apiadresse/dataloader
    pullPolicy: IfNotPresent
    tag: "1.0"
  s3EndpointUrl: "https://api.minio-siaf.apps.app1.numerique-interieur.com/"